import React, { useState } from 'react';
import { CopyIcon, DownloadIcon } from './Icons';
import { jsPDF } from "jspdf";

interface OutputSectionProps {
  content: string;
  onChange: (value: string) => void;
}

const OutputSection: React.FC<OutputSectionProps> = ({ content, onChange }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const handleDownloadTxt = () => {
    const element = document.createElement("a");
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "cover-letter.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadPdf = () => {
    const doc = new jsPDF();
    
    // Page setup
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);
    
    // Content
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    
    // Split text to fit page width
    const splitText = doc.splitTextToSize(content, maxLineWidth);
    
    // Add text to PDF starting at the top margin (no extra header title)
    doc.text(splitText, margin, margin);
    
    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Generated by AI Cover Letter Nexus", margin, doc.internal.pageSize.getHeight() - 10);
    
    doc.save("cover-letter.pdf");
  };

  if (!content) return null;

  return (
    <div className="mt-8 sm:mt-12 animate-fade-in-up">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-4 gap-3 sm:gap-4">
        <h2 className="text-xl sm:text-2xl font-semibold text-transparent bg-clip-text bg-gradient-to-r from-secondary-400 to-primary-500">
          Generated Cover Letter
        </h2>
        <div className="flex flex-wrap space-x-2 sm:space-x-3 w-full sm:w-auto justify-end">
          <button 
            onClick={handleCopy}
            className="flex items-center justify-center space-x-1 sm:space-x-2 px-2 sm:px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs sm:text-sm font-medium transition-colors border border-slate-700 hover:border-slate-600"
            title="Copy to Clipboard"
          >
            <CopyIcon />
            <span className="hidden sm:inline">{copied ? 'Copied!' : 'Copy'}</span>
          </button>
          <button 
            onClick={handleDownloadTxt}
            className="flex items-center justify-center space-x-1 sm:space-x-2 px-2 sm:px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs sm:text-sm font-medium transition-colors border border-slate-700 hover:border-slate-600"
            title="Download as Text"
          >
             <span className="text-xs font-mono border border-slate-500 rounded px-1">TXT</span>
             <span className="hidden sm:inline">Download</span>
          </button>
          <button 
            onClick={handleDownloadPdf}
            className="flex items-center justify-center space-x-1 sm:space-x-2 px-3 sm:px-4 py-2 bg-primary-700 hover:bg-primary-600 text-white rounded-lg text-xs sm:text-sm font-medium transition-colors border border-primary-600 hover:border-primary-500 shadow-lg shadow-primary-900/20"
            title="Download as PDF"
          >
            <DownloadIcon />
            <span>Download PDF</span>
          </button>
        </div>
      </div>

      <div className="relative group">
        <div className="absolute -inset-0.5 bg-gradient-to-r from-secondary-500 to-primary-600 rounded-xl opacity-30 group-hover:opacity-50 blur transition duration-500"></div>
        <div className="relative bg-slate-900 rounded-xl border border-slate-800 shadow-2xl overflow-hidden">
          <textarea
            value={content}
            onChange={(e) => onChange(e.target.value)}
            className="w-full h-[400px] sm:h-[500px] md:h-[600px] p-4 sm:p-6 md:p-8 bg-transparent text-slate-300 text-sm sm:text-base md:text-lg leading-relaxed focus:outline-none resize-y font-sans placeholder-slate-600 block"
            spellCheck="false"
          />
        </div>
      </div>
      <div className="mt-2 text-right">
         <span className="text-xs text-slate-600">Word count: {content.split(/\s+/).filter(w => w.length > 0).length}</span>
      </div>
    </div>
  );
};

export default OutputSection;